[package]
name = "ftran"
version = "0.0.1"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
axum-client-ip = "0.7.0"
thiserror = "2.0.12"
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread"] }

[profile.dev]
opt-level = 2
